In [12]:
import nomic
from nomic import atlas
import numpy as np
import os
from dotenv import load_dotenv
load_dotenv()

api_key = os.getenv('NOMIC_API_KEY')
nomic.login(api_key)       

num_embeddings = 10000
embeddings = np.random.rand(num_embeddings, 256)
        
project = atlas.map_embeddings(embeddings=embeddings)
print(project.maps)

2023-08-02 12:10:22.527 | WARNING  | nomic.atlas:map_embeddings:91 - An ID field was not specified in your data so one was generated for you in insertion order.
2023-08-02 12:10:36.658 | INFO     | nomic.project:_create_project:779 - Creating project `frightened-bronco` in organization `myemailiskevin`
2023-08-02 12:10:44.599 | INFO     | nomic.atlas:map_embeddings:107 - Uploading embeddings to Atlas.
100%|██████████| 2/2 [00:06<00:00,  3.44s/it]
2023-08-02 12:10:51.789 | INFO     | nomic.project:_add_data:1401 - Upload succeeded.
2023-08-02 12:10:51.800 | INFO     | nomic.atlas:map_embeddings:126 - Embedding upload succeeded.
2023-08-02 12:11:03.473 | INFO     | nomic.project:create_index:1111 - Created map `frightened-bronco` in project `frightened-bronco`: https://atlas.nomic.ai/map/c5cd04b1-e129-4344-b347-e53a6962f232/b6283232-68f5-4c81-862c-79ec2369c035
2023-08-02 12:11:03.482 | INFO     | nomic.atlas:map_embeddings:139 - frightened-bronco: https://atlas.nomic.ai/map/c5cd04b1-e129

[frightened-bronco: https://atlas.nomic.ai/map/c5cd04b1-e129-4344-b347-e53a6962f232/b6283232-68f5-4c81-862c-79ec2369c035]


When you run the above code, you should get something like this at the end:

frightened-bronco: https://atlas.nomic.ai/map/c5cd04b1-e129-4344-b347-e53a6962f232/b6283232-68f5-4c81-862c-79ec2369c035

Open the URL

```
2023-08-02 12:10:22.527 | WARNING  | nomic.atlas:map_embeddings:91 - An ID field was not specified in your data so one was generated for you in insertion order.
2023-08-02 12:10:36.658 | INFO     | nomic.project:_create_project:779 - Creating project `frightened-bronco` in organization `myemailiskevin`
2023-08-02 12:10:44.599 | INFO     | nomic.atlas:map_embeddings:107 - Uploading embeddings to Atlas.
100%|██████████| 2/2 [00:06<00:00,  3.44s/it]
2023-08-02 12:10:51.789 | INFO     | nomic.project:_add_data:1401 - Upload succeeded.
2023-08-02 12:10:51.800 | INFO     | nomic.atlas:map_embeddings:126 - Embedding upload succeeded.
2023-08-02 12:11:03.473 | INFO     | nomic.project:create_index:1111 - Created map `frightened-bronco` in project `frightened-bronco`: https://atlas.nomic.ai/map/c5cd04b1-e129-4344-b347-e53a6962f232/b6283232-68f5-4c81-862c-79ec2369c035
2023-08-02 12:11:03.482 | INFO     | nomic.atlas:map_embeddings:139 - frightened-bronco: https://atlas.nomic.ai/map/c5cd04b1-e129-4344-b347-e53a6962f232/b6283232-68f5-4c81-862c-79ec2369c035
[frightened-bronco: https://atlas.nomic.ai/map/c5cd04b1-e129-4344-b347-e53a6962f232/b6283232-68f5-4c81-862c-79ec2369c035]
```

You should see something like this:


![Shows a visualization of the vectors generated above](..//frightened-bronco.png "Nomic Atlas Vector DB isualization")
